# Generated by Django 5.2.1 on 2025-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='media/')),
                ('seller', models.CharField(max_length=120)),
                ('oldPrice', models.FloatField()),
                ('newPrice', models.FloatField()),
                ('rating', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('watched', models.IntegerField()),
                ('liked', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
