# Generated by Django 5.2.1 on 2025-05-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_classes_subject_alter_category_name_doctors_patients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qulayliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='disease_category',
        ),
        migrations.RemoveField(
            model_name='students',
            name='main_subject',
        ),
        migrations.RemoveField(
            model_name='students',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('weekdays_price', models.FloatField()),
                ('weekend_price', models.FloatField()),
                ('text', models.TextField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('qulayliklar', models.ManyToManyField(to='main.qulayliklar')),
            ],
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
