# Generated by Django 5.2.1 on 2025-05-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
