# Generated by Django 5.2.1 on 2025-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='new',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
