# Generated by Django 5.2.1 on 2025-05-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_products_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
