# Generated by Django 5.2.1 on 2025-05-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
