# Generated by Django 5.2.1 on 2025-05-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
