# Generated by Django 5.2.1 on 2025-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_news_alter_category_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
