# Generated by Django 5.2.1 on 2025-06-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('review', models.CharField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
    ]
