# Generated by Django 5.2.1 on 2025-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
